#!/bin/bash
echo "synching git"
git pull
echo "preparing build"
java -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M -jar ../../opt/play-2.1.3/framework/sbt/sbt-launch.jar -Dsbt.log.noformat=true dist
cd dist
echo "build done..."
echo "copying build to deployed dir ..."
unzip pharmakhana-1.0-SNAPSHOT.zip
cd pharmakhana-1.0-SNAPSHOT/
chmod 777 start
echo "nohup  ./start -Dhttp.port=80 &"

